package errorhandling;

public class MyClass {
  public void myfunct2() throws MyException{
	  System.out.println("inside my function 2 inside MyClass");
  }
}
